function [fitresult_temp5, gof] = Temp_profile_5bar(xEthanol5, Temp_5bar)
%CREATEFIT(XETHANOL5,TEMP_5BAR)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xEthanol5
%      Y Output: Temp_5bar
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Jul-2020 05:02:10


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xEthanol5, Temp_5bar );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.999999999976934;

% Fit model to data.
[fitresult_temp5, gof] = fit( xData, yData, ft, opts );



