function [fitresult_temp1, gof] = Temp_profile_1bar(xEthanol, Temp_1bar)
%CREATEFIT(XETHANOL,TEMP_1BAR)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xEthanol
%      Y Output: Temp_1bar
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Jul-2020 05:01:00


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xEthanol, Temp_1bar );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.999999999536717;

% Fit model to data.
[fitresult_temp1, gof] = fit( xData, yData, ft, opts );




