function [fitresult, gof] = X_vs_Y_Ethanol(xEthanol, yEthanol)
%CREATEFIT(XETHANOL,YETHANOL)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xEthanol
%      Y Output: yEthanol
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Jul-2020 03:07:18


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xEthanol, yEthanol );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.99999999971899;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%h = plot( fitresult, xData, yData );







