function [fitresult, gof] = X_vs_Temp_Ethanol_1_bar(xEthanol, T_sat_)
%CREATEFIT(XETHANOL,T_SAT_)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xEthanol
%      Y Output: T_sat_
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Jul-2020 03:10:04


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xEthanol, T_sat_ );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.999999999999965;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.

%h = plot( fitresult, xData, yData );



