function [fitresult, gof] = X_vs_T_sat_Ethanol_5bars(xEthanol5, TC5)
%CREATEFIT(XETHANOL5,TC5)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xEthanol5
%      Y Output: TC5
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Jul-2020 03:21:12


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xEthanol5, TC5 );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 1;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%h = plot( fitresult, xData, yData );



